/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeIndexRouteImport } from './routes/resume/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ResumeCompanyRouteImport } from './routes/resume/$company'
import { Route as ProjectsProjectRouteImport } from './routes/projects/$project'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeIndexRoute = ResumeIndexRouteImport.update({
  id: '/resume/',
  path: '/resume/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeCompanyRoute = ResumeCompanyRouteImport.update({
  id: '/resume/$company',
  path: '/resume/$company',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectRoute = ProjectsProjectRouteImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/resume/$company': typeof ResumeCompanyRoute
  '/projects': typeof ProjectsIndexRoute
  '/resume': typeof ResumeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/resume/$company': typeof ResumeCompanyRoute
  '/projects': typeof ProjectsIndexRoute
  '/resume': typeof ResumeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/resume/$company': typeof ResumeCompanyRoute
  '/projects/': typeof ProjectsIndexRoute
  '/resume/': typeof ResumeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$project'
    | '/resume/$company'
    | '/projects'
    | '/resume'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/$project' | '/resume/$company' | '/projects' | '/resume'
  id:
    | '__root__'
    | '/'
    | '/projects/$project'
    | '/resume/$company'
    | '/projects/'
    | '/resume/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectRoute: typeof ProjectsProjectRoute
  ResumeCompanyRoute: typeof ResumeCompanyRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ResumeIndexRoute: typeof ResumeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/': {
      id: '/resume/'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$company': {
      id: '/resume/$company'
      path: '/resume/$company'
      fullPath: '/resume/$company'
      preLoaderRoute: typeof ResumeCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectRoute: ProjectsProjectRoute,
  ResumeCompanyRoute: ResumeCompanyRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ResumeIndexRoute: ResumeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
